services:
  postgres:
    image: postgres:16.4
    restart: always
    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_pass
      POSTGRES_DB: youtube
    ports:
      - 8787:5432
